# fly.toml app configuration file generated for practice-wild-dew-9880 on 2024-11-09T03:38:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'practice-wild-dew-9880'
primary_region = 'jnb'

[build]
  PORT="3000"
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
